CREATE OR REPLACE TYPE HOSPITALARIO.OBJ_CGF_CAMA_SERVICIO AS OBJECT
(
CfgUsalServCamaId NUMBER,             
CodAsistencial    VARCHAR2(100),
UsalServId        NUMBER,
ServicioId        NUMBER,
SalaId            NUMBER,
HabitacionId      NUMBER,
CamaId            NUMBER,
Disponible        NUMBER,
EstadoCama        NUMBER,
UnidadSaludId     NUMBER,
FecInicio         DATE,   
FecFin            DATE);






CREATE INDEX IDX_RELUSALSER_SERVICIO ON HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS
(SERVICIO_ID);

CREATE INDEX IDX_RELUSALSER_USALUD ON HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS
(UNIDAD_SALUD_ID);


CREATE INDEX IDX_RELUSALSER_SERV_USALD ON HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS
(SERVICIO_ID, UNIDAD_SALUD_ID);