      
      
ALTER TABLE HOSPITALARIO.SNH_MST_DIAGNOSTICOS ADD (USUARIO_ELIMINA VARCHAR2(50));

ALTER TABLE HOSPITALARIO.SNH_MST_DIAGNOSTICOS ADD (FECHA_ELIMINA DATE);


ALTER TABLE HOSPITALARIO.SNH_MST_DIAGNOSTICOS ADD (USUARIO_PASIVA VARCHAR2(50));

ALTER TABLE HOSPITALARIO.SNH_MST_DIAGNOSTICOS ADD (FECHA_PASIVA DATE);