CREATE SEQUENCE HOSPITALARIO.SNH_S_INDISPONIBILIDAD_CAMA_ID
  START WITH 1
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER
  NOKEEP
  GLOBAL;

GRANT ALTER, SELECT ON HOSPITALARIO.SNH_S_INDISPONIBILIDAD_CAMA_ID TO CATALOGOS, SEGURIDAD, VIGILANCIA, SIPAI; 



CREATE TABLE HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS
(INDISPONIBILIDAD_CAMA_ID  NUMBER(10)          DEFAULT HOSPITALARIO.SNH_S_INDISPONIBILIDAD_CAMA_ID.NEXTVAL CONSTRAINT PRK_INDISP_CAMAS PRIMARY KEY NOT NULL,
 CFG_USLD_SERVICIO_CAMA_ID NUMBER(10),  --          CONSTRAINT NNC_INDISP_USERSERV_CAMAS NOT NULL,
 CAMA_ID                   NUMBER(10)          CONSTRAINT NNC_INDISP_CAMA_ID NOT NULL,
 CAUSA_ID                  NUMBER(10)          CONSTRAINT NNC_INDISP_CAUSA_ID NOT NULL,
 DESCRIPCION_SALIDA        VARCHAR2(1000 BYTE) CONSTRAINT NNC_INDISP_DESC_SALIDA NOT NULL,
 DESCRIPCION_RETORNO       VARCHAR2(1000 BYTE),  -- CONSTRAINT NNC_INDISP_DESC_SALIDA NOT NULL,
 FECHA_SALIDA              TIMESTAMP(0)        CONSTRAINT NNC_INDISP_FEC_SALIDA NOT NULL,
 HORA_SALIDA               VARCHAR2(10 BYTE)   CONSTRAINT NNC_INDISP_HR_SALIDA NOT NULL,
 FECHA_RETORNO             TIMESTAMP(0),
 HORA_RETORNO              VARCHAR2(10 BYTE),
 ESTADO_REGISTRO_ID        NUMBER(10)         CONSTRAINT NNC_INDISP_ESTADOREG NOT NULL,   
 USUARIO_REGISTRO          VARCHAR2(50 BYTE)  CONSTRAINT NNC_INDISP_USR_REGISTRO NOT NULL,
 FECHA_REGISTRO            TIMESTAMP(0)       DEFAULT CURRENT_TIMESTAMP CONSTRAINT NNC_INDISP_FEC_REGISTRO NOT NULL,
 USUARIO_MODIFICACION      VARCHAR2(50 BYTE),
 FECHA_MODIFICACION        TIMESTAMP(0),
 USUARIO_PASIVA            VARCHAR2(50 BYTE),
 FECHA_PASIVA              TIMESTAMP(0),
 USUARIO_ELIMINA           VARCHAR2(50 BYTE),
 FECHA_ELIMINA             TIMESTAMP(0)   
);


CREATE OR REPLACE TRIGGER TRG_AUD_SNH_INDISP_CAMAS
BEFORE INSERT OR UPDATE ON HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS FOR EACH ROW
BEGIN
    IF INSERTING THEN
       :NEW.FECHA_REGISTRO  := SYSDATE;
    ELSE
       IF :NEW.USUARIO_MODIFICACION IS NULL THEN
           RAISE_APPLICATION_ERROR (-20000, 'El usuario modificación no puede quedar nulo.');
       ELSE
       :NEW.FECHA_MODIFICACION   := SYSDATE;
       END IF;
    END IF;
END;
/

CREATE INDEX IDX_INDISPCAMA_ESTADO_REGISTRO ON HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS
(ESTADO_REGISTRO_ID);

CREATE INDEX IDX_INDISPCAMA_CAMAID ON HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS
(CAMA_ID);

CREATE INDEX IDX_INDISPCAMA_CAUSAID ON HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS
(CAUSA_ID);

CREATE INDEX IDX_INDISPCAMA_USR_REGISTRO ON HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS
(USUARIO_REGISTRO);




ALTER TABLE HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS ADD (
  CONSTRAINT FRK_INDISP_CFG_USLD_SERV_CAMA
  FOREIGN KEY (CFG_USLD_SERVICIO_CAMA_ID) 
  REFERENCES HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS (CFG_USLD_SERVICIO_CAMA_ID)
  ENABLE VALIDATE,
  CONSTRAINT FRK_INDISP_CAMA_ID 
  FOREIGN KEY (CAMA_ID) 
  REFERENCES HOSPITALARIO.SNH_CAT_CAMAS (CAMA_ID)
  ENABLE VALIDATE,
  CONSTRAINT FRK_INDISP_CAUSA_ID 
  FOREIGN KEY (CAUSA_ID) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_INDISP_ESTADO_REG_ID 
  FOREIGN KEY (ESTADO_REGISTRO_ID) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_INDISP_USR_REGISTRO 
  FOREIGN KEY (USUARIO_REGISTRO) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_INDISP_USR_MODIFCACION 
  FOREIGN KEY (USUARIO_MODIFICACION) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_INDISP_USR_PASIVO 
  FOREIGN KEY (USUARIO_PASIVA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_INDISP_USR_ELIMINA 
  FOREIGN KEY (USUARIO_ELIMINA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE    
  );
