CREATE SEQUENCE HOSPITALARIO.SNH_S_ADMSRV_CAMA_ID
  START WITH 1
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER
  NOKEEP
  GLOBAL;

GRANT ALTER, SELECT ON HOSPITALARIO.SNH_S_ADMSRV_CAMA_ID TO CATALOGOS, SEGURIDAD, VIGILANCIA, SIPAI; 



CREATE TABLE HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(ADMISION_SRV_CAMA_ID             NUMBER(10)        DEFAULT HOSPITALARIO.SNH_S_ADMSRV_CAMA_ID.NEXTVAL CONSTRAINT PRK_ADMSRVCAMAS_ID PRIMARY KEY NOT NULL,
 CFG_USLD_SERVICIO_CAMA_ID        NUMBER(10)        CONSTRAINT NNC_ADMSRVCAMAS_SERV_CAMA_ID NOT NULL,  
 ADMISION_SERVICIO_ID             NUMBER(10)        CONSTRAINT NNC_ADMSRVCAMAS_ADM_SERV_ID NOT NULL,
 FECHA_INI                        TIMESTAMP(0)      CONSTRAINT NNC_ADMSRVCAMAS_FEC_INI NOT NULL,
 HORA_INI                         VARCHAR2(10 BYTE) CONSTRAINT NNC_ADMSRVCAMAS_HR_INI NOT NULL,
 FECHA_FIN                        TIMESTAMP(0),
 HORA_FIN                         VARCHAR2(10 BYTE), 
 IS_LAST                          NUMBER(1)         CONSTRAINT NNC_ADMSRVCAMAS_ISLAST NOT NULL,  
 ESTADO_REGISTRO_ID               NUMBER(10)        CONSTRAINT NNC_ADMSRVCAMAS_ESTADOREG NOT NULL,   
 USUARIO_REGISTRO                 VARCHAR2(50 BYTE) CONSTRAINT NNC_ADMSRVCAMAS_USR_REGISTRO NOT NULL,
 FECHA_REGISTRO                   TIMESTAMP(0)      DEFAULT CURRENT_TIMESTAMP CONSTRAINT NNC_ADMSRVCAMAS_FEC_REGISTRO NOT NULL,
 USUARIO_MODIFICACION             VARCHAR2(50 BYTE),
 FECHA_MODIFICACION               TIMESTAMP(0),
 USUARIO_PASIVA                   VARCHAR2(50 BYTE),
 FECHA_PASIVA                     TIMESTAMP(0),
 USUARIO_ELIMINA                  VARCHAR2(50 BYTE),
 FECHA_ELIMINA                    TIMESTAMP(0)   
);

CREATE INDEX IDX_ADMSRVCAMAS_CFG_SERVCAMA ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(CFG_USLD_SERVICIO_CAMA_ID);


CREATE INDEX IDX_ADMSRVCAMAS_ADMINSERV ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(ADMISION_SERVICIO_ID);

CREATE INDEX IDX_ADMSRVCAMAS_ADMINSERV_EST ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(ADMISION_SERVICIO_ID, ESTADO_REGISTRO_ID);

CREATE INDEX IDX_ADMSRVCAMAS_ADMINSERV_LAST ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(ADMISION_SERVICIO_ID, IS_LAST);


CREATE INDEX IDX_ADMSRVCAMAS_CFGCAMA_LAST ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(CFG_USLD_SERVICIO_CAMA_ID, IS_LAST);


CREATE INDEX IDX_ADMSRVCAMA_CFGCAMASER_LAST ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(CFG_USLD_SERVICIO_CAMA_ID, ADMISION_SERVICIO_ID, IS_LAST);


CREATE INDEX IDX_ADMSRVCAMAS_ESTADOREG ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS
(ESTADO_REGISTRO_ID);


CREATE OR REPLACE TRIGGER TRG_AUD_SNH_ADMSRVCAMAS
BEFORE INSERT OR UPDATE ON HOSPITALARIO.SNH_REL_ADMSRV_CAMAS FOR EACH ROW
BEGIN
    IF INSERTING THEN
       :NEW.FECHA_REGISTRO  := SYSDATE;
    ELSE
       IF :NEW.USUARIO_MODIFICACION IS NULL THEN
           RAISE_APPLICATION_ERROR (-20000, 'El usuario modificación no puede quedar nulo.');
       ELSE
       :NEW.FECHA_MODIFICACION   := SYSDATE;
       END IF;
    END IF;
END;
/


ALTER TABLE HOSPITALARIO.SNH_REL_ADMSRV_CAMAS ADD (
  CONSTRAINT FRK_ADMSRVCAMAS_CFG_USLD_SERV
  FOREIGN KEY (CFG_USLD_SERVICIO_CAMA_ID) 
  REFERENCES HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS (CFG_USLD_SERVICIO_CAMA_ID)
  ENABLE VALIDATE,
  CONSTRAINT FRK_ADMSRVCAMAS_ADMIN_SERV_ID
  FOREIGN KEY (ADMISION_SERVICIO_ID) 
  REFERENCES HOSPITALARIO.SNH_MST_ADMISION_SERVICIOS (ADMISION_SERVICIO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_ADMSRVCAMAS_ESTADO_REG_ID 
  FOREIGN KEY (ESTADO_REGISTRO_ID) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_ADMSRVCAMAS_USR_REGISTRO 
  FOREIGN KEY (USUARIO_REGISTRO) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_ADMSRVCAMAS_USR_MOD 
  FOREIGN KEY (USUARIO_MODIFICACION) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_ADMSRVCAMAS_USR_PASIVO 
  FOREIGN KEY (USUARIO_PASIVA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_ADMSRVCAMAS_USR_ELIMINA 
  FOREIGN KEY (USUARIO_ELIMINA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE    
  );
