CREATE SEQUENCE HOSPITALARIO.SNH_S_CAMA_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER
  NOKEEP
  GLOBAL;
  

GRANT ALTER, SELECT ON HOSPITALARIO.SNH_S_CAMA_ID TO CATALOGOS, SEGURIDAD, VIGILANCIA, SIPAI; 
  
 
RENAME SNH_CAT_CAMAS TO SNH_CAT_CAMAS_1;
--RENAME SNH_CAT_CAMAS_1 TO SNH_CAT_CAMAS;


--RENAME SNH_CAT_CAMAS TO SNH_CAT_CAMAS_1;
--RENAME SNH_CAT_CAMAS_2 TO SNH_CAT_CAMAS;

 
CREATE TABLE HOSPITALARIO.SNH_CAT_CAMAS
(
  CAMA_ID                NUMBER(10)         DEFAULT HOSPITALARIO.SNH_S_CAMA_ID.NEXTVAL CONSTRAINT PRK_CAMAS_ID PRIMARY KEY NOT NULL,
  NOMBRE                 VARCHAR2(50 BYTE)  CONSTRAINT NNC_CAMA_NOMBRE NOT NULL,
  CODIGO_ADMINISTRATIVO  VARCHAR2(10 BYTE)  CONSTRAINT NNC_CAMA_COD_ADMIN NOT NULL,
  NO_SERIE               VARCHAR2(50 BYTE),
  ESTADO_CAMA            NUMBER(10)         CONSTRAINT NNC_CAMA_ESTADCAMA NOT NULL,
  ESTADO_REGISTRO_ID     NUMBER(10)         CONSTRAINT NNC_CAMA_ESTADOREG NOT NULL,   
  USUARIO_REGISTRO       VARCHAR2(50 BYTE)  CONSTRAINT NNC_CAMA_USR_REGISTRO NOT NULL,
  FECHA_REGISTRO         TIMESTAMP(0)       DEFAULT CURRENT_TIMESTAMP CONSTRAINT NNC_CAMA_FEC_REGISTRO NOT NULL,
  USUARIO_MODIFICACION   VARCHAR2(50 BYTE),
  FECHA_MODIFICACION     TIMESTAMP(0),
  USUARIO_PASIVA         VARCHAR2(50 BYTE),
  FECHA_PASIVA           TIMESTAMP(0),
  USUARIO_ELIMINA        VARCHAR2(50 BYTE),
  FECHA_ELIMINA          TIMESTAMP(0)   
);


CREATE OR REPLACE TRIGGER TRG_AUD_SNH_CAMAS
BEFORE INSERT OR UPDATE ON HOSPITALARIO.SNH_CAT_CAMAS FOR EACH ROW
BEGIN
    IF INSERTING THEN
       :NEW.FECHA_REGISTRO  := SYSDATE;
    ELSE
       IF :NEW.USUARIO_MODIFICACION IS NULL THEN
           RAISE_APPLICATION_ERROR (-20000, 'El usuario modificación no puede quedar nulo.');
       ELSE
       :NEW.FECHA_MODIFICACION   := SYSDATE;
       END IF;
    END IF;
END;
/

CREATE INDEX IDX_CATCAMA_ESTADO_REGISTRO ON HOSPITALARIO.SNH_CAT_CAMAS
(ESTADO_REGISTRO_ID);

CREATE INDEX IDX_CATCAMA_CODADMIN ON HOSPITALARIO.SNH_CAT_CAMAS
(CODIGO_ADMINISTRATIVO);


CREATE INDEX IDX_CATCAMA_ESTADO_CAMA ON HOSPITALARIO.SNH_CAT_CAMAS
(ESTADO_CAMA);


CREATE INDEX IDX_CATCAMA_NO_SERIE ON HOSPITALARIO.SNH_CAT_CAMAS
(NO_SERIE);

CREATE INDEX IDX_CATCAMA_USR_REGISTRO ON HOSPITALARIO.SNH_CAT_CAMAS
(USUARIO_REGISTRO);


ALTER TABLE HOSPITALARIO.SNH_CAT_CAMAS ADD (
  CONSTRAINT FRK_CAMAS_ESTADO_PX_ID
  FOREIGN KEY (ESTADO_CAMA ) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CAMAS_ESTADO_REG_ID 
  FOREIGN KEY (ESTADO_REGISTRO_ID) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_CAMAS_USR_REGISTRO 
  FOREIGN KEY (USUARIO_REGISTRO) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CAMAS_USR_MODIFCACION 
  FOREIGN KEY (USUARIO_MODIFICACION) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CAMAS_USR_PASIVO 
  FOREIGN KEY (USUARIO_PASIVA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE  
  );

--DROP TABLE SNH_CAT_CAMAS_1
--SNH_DET_ADMSRV_CAMAS
--
--
--select *
--from SNH_CAT_CAMAS

