--SELECT MAX (UND_SALUD_SERVICIO_ID)
--FROM SNH_REL_UND_SALUD_SERVICIOS;



--SELECT SEQ_SNH_UND_SALUD_SERVICIO_ID.CURRVAL
--FROM DUAL;


ALTER TABLE HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS MODIFY (UND_SALUD_SERVICIO_ID DEFAULT HOSPITALARIO.SEQ_SNH_UND_SALUD_SERVICIO_ID.NEXTVAL);
ALTER TABLE HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS ADD(FECHA_ELIMINA TIMESTAMP(0));
ALTER TABLE HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS ADD(USUARIO_ELIMINA VARCHAR2(50));
ALTER TABLE HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS ADD(FECHA_PASIVA TIMESTAMP(0));
ALTER TABLE HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS ADD(USUARIO_PASIVA VARCHAR2(50));


CREATE OR REPLACE TRIGGER TRG_AUD_SNH_REL_USALUDSERV
BEFORE INSERT OR UPDATE ON HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS FOR EACH ROW
BEGIN
    IF INSERTING THEN
       :NEW.FECHA_REGISTRO  := SYSDATE;
    ELSE
       IF :NEW.USUARIO_MODIFICACION IS NULL THEN
           RAISE_APPLICATION_ERROR (-20000, 'El usuario modificación no puede quedar nulo.');
       ELSE
       :NEW.FECHA_MODIFICACION   := SYSDATE;
       END IF;
    END IF;
END;
/


ALTER TABLE HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS ADD (
  CONSTRAINT FRK_RELUSALSER_ESTADO_REG_ID 
  FOREIGN KEY (ESTADO_REGISTRO) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_RELUSALSER_USR_REGISTRO 
  FOREIGN KEY (USUARIO_REGISTRO) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_RELUSALSER_USR_MODIFCACION 
  FOREIGN KEY (USUARIO_MODIFICACION) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_RELUSALSER_USR_PASIVO 
  FOREIGN KEY (USUARIO_PASIVA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_RELUSALSER_USR_ELIMINA 
  FOREIGN KEY (USUARIO_ELIMINA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE    
  );
  
  
 