CREATE SEQUENCE HOSPITALARIO.SNH_S_CFG_SERV_CAMAS_ID
  START WITH 1
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER
  NOKEEP
  GLOBAL;

GRANT ALTER, SELECT ON HOSPITALARIO.SNH_S_CFG_SERV_CAMAS_ID TO CATALOGOS, SEGURIDAD, VIGILANCIA, SIPAI; 



CREATE TABLE HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(CFG_USLD_SERVICIO_CAMA_ID NUMBER(10) DEFAULT HOSPITALARIO.SNH_S_CFG_SERV_CAMAS_ID.NEXTVAL CONSTRAINT PRK_USERSERV_CAMAS PRIMARY KEY NOT NULL,
 UND_SALUD_SERVICIO_ID     NUMBER(10)         CONSTRAINT NNC_USALUD_SERV_ID NOT NULL,         
 CODIGO_ASISTENCIAL        VARCHAR2(50 BYTE)  CONSTRAINT NNC_CODIGO_ASISTENCIAL NOT NULL,
 SALA_ID                   NUMBER(10),
 HABITACION_ID             NUMBER(10)         CONSTRAINT NNC_CFG_SERV_HABITACION_ID NOT NULL,
 CAMA_ID                   NUMBER(10)         CONSTRAINT NNC_CFG_SERV_CAMA_ID NOT NULL,
 DISPONIBLE                NUMBER(1)          CONSTRAINT NNC_CFG_SERV_DISPONIBLE NOT NULL,
 CENSABLE                  NUMBER(1)          CONSTRAINT NNC_CFG_SERV_CENSABLE NOT NULL,
 ESTADO_CAMA_ID            NUMBER(10)         CONSTRAINT NNC_CFG_SERV_ESTADO_CAMA NOT NULL,
 IS_LAST                   NUMBER(1)          CONSTRAINT NNC_CFG_SERV_IS_LAST NOT NULL,
 ESTADO_REGISTRO_ID        NUMBER(10)         CONSTRAINT NNC_CFG_SERV_ESTADOREG NOT NULL,   
 USUARIO_REGISTRO          VARCHAR2(50 BYTE)  CONSTRAINT NNC_CFG_SERV_USR_REGISTRO NOT NULL,
 FECHA_REGISTRO            TIMESTAMP(0)       DEFAULT CURRENT_TIMESTAMP CONSTRAINT NNC_CFG_SERV_FEC_REGISTRO NOT NULL,
 USUARIO_MODIFICACION      VARCHAR2(50 BYTE),
 FECHA_MODIFICACION        TIMESTAMP(0),
 USUARIO_PASIVA            VARCHAR2(50 BYTE),
 FECHA_PASIVA              TIMESTAMP(0),
 USUARIO_ELIMINA           VARCHAR2(50 BYTE),
 FECHA_ELIMINA             TIMESTAMP(0)   
);

--ALTER TABLE HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS ADD(IS_LAST NUMBER(1) CONSTRAINT NNC_CFG_SERV_IS_LAST NOT NULL);

CREATE OR REPLACE TRIGGER TRG_AUD_SNH_CFG_SERV
BEFORE INSERT OR UPDATE ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS FOR EACH ROW
BEGIN
    IF INSERTING THEN
       :NEW.FECHA_REGISTRO  := SYSDATE;
    ELSE
       IF :NEW.USUARIO_MODIFICACION IS NULL THEN
           RAISE_APPLICATION_ERROR (-20000, 'El usuario modificación no puede quedar nulo.');
       ELSE
       :NEW.FECHA_MODIFICACION   := SYSDATE;
       END IF;
    END IF;
END;
/

CREATE INDEX IDX_CFGCAMA_ESTADO_REGISTRO ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(ESTADO_REGISTRO_ID);

CREATE INDEX IDX_CFGCAMA_CAMAID ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(CAMA_ID);

CREATE INDEX IDX_CFGCAMA_CAUSAID ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(UND_SALUD_SERVICIO_ID);

CREATE INDEX IDX_CFGCAMA_CODASISTENCIAL ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(CODIGO_ASISTENCIAL);

CREATE INDEX IDX_CFGCAMA_DISPONIBLE ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(DISPONIBLE);

CREATE INDEX IDX_CFGCAMA_USALSERV_DIS ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(UND_SALUD_SERVICIO_ID, DISPONIBLE);


CREATE INDEX IDX_CFGCAMA_CENSABLE ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(CENSABLE);


CREATE INDEX IDX_CFGCAMA_USALSERV_CENSABLE ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(UND_SALUD_SERVICIO_ID, CENSABLE);


CREATE INDEX IDX_CFGCAMA_ESTADO_CAMA ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(ESTADO_CAMA_ID);


CREATE INDEX IDX_CFGCAMA_IS_LAST ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(IS_LAST);


CREATE INDEX IDX_CFGCAMA_CAMA_ISLAST ON HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS
(CAMA_ID, IS_LAST);

CREATE INDEX IDX_INDISPCAMA_USR_REGISTRO ON HOSPITALARIO.SNH_MST_INDISPONIBILIDAD_CAMAS
(USUARIO_REGISTRO);

ALTER TABLE HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS ADD (
  CONSTRAINT FRK_CFGSERV_CAMA_ID 
  FOREIGN KEY (CAMA_iD) 
  REFERENCES HOSPITALARIO.SNH_CAT_CAMAS (CAMA_ID)
  ENABLE VALIDATE);

ALTER TABLE HOSPITALARIO.SNH_CFG_USERVICIOS_CAMAS ADD (
  CONSTRAINT FRK_CFGSERV_USAL_SERV_ID 
  FOREIGN KEY (UND_SALUD_SERVICIO_ID) 
  REFERENCES HOSPITALARIO.SNH_REL_UND_SALUD_SERVICIOS (UND_SALUD_SERVICIO_ID)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CFGSERV_CAMA_ID 
  FOREIGN KEY (CAMA_iD) 
  REFERENCES HOSPITALARIO.SNH_CAT_CAMAS (CAMA_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_CFGSERV_ESTADO_CAMA_ID 
  FOREIGN KEY (ESTADO_CAMA_ID) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CFGSERV_ESTADO_REG_ID 
  FOREIGN KEY (ESTADO_REGISTRO_ID) 
  REFERENCES CATALOGOS.SBC_CAT_CATALOGOS (CATALOGO_ID)
  ENABLE VALIDATE,  
  CONSTRAINT FRK_CFGSERV_USR_REGISTRO 
  FOREIGN KEY (USUARIO_REGISTRO) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CFGSERV_USR_MODIFCACION 
  FOREIGN KEY (USUARIO_MODIFICACION) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CFGSERV_USR_PASIVO 
  FOREIGN KEY (USUARIO_PASIVA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE,
  CONSTRAINT FRK_CFGSERV_USR_ELIMINA 
  FOREIGN KEY (USUARIO_ELIMINA) 
  REFERENCES SEGURIDAD.SCS_MST_USUARIOS (USERNAME)
  ENABLE VALIDATE    
  );
