CREATE GLOBAL TEMPORARY TABLE SIPAI.SIPAI_CTRL_VAC_PAGINADAS_TMP
(
  LINEA              NUMBER,
  CONTROL_VACUNA_ID  NUMBER
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


GRANT INSERT, SELECT ON SIPAI.SIPAI_CTRL_VAC_PAGINADAS_TMP TO HOSPITALARIO, CATALOGOS, VIGILANCIA, SEGURIDAD;