ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (ESTADO_REGISTRO_ID  NUMBER(10) CONSTRAINT NNC_ADMPROC_ESTADOREG NOT NULL);

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (USUARIO_PASIVA  VARCHAR2(50));

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (FECHA_PASIVA  TIMESTAMP(0));

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (USUARIO_ELIMINA  VARCHAR2(50));

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (FECHA_ELIMINA  VARCHAR2(50));

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (TIPO_PROCEDIMIENTO_ID  NUMBER(10) CONSTRAINT NNC_ADMPROC_TIPPROCED NOT NULL);

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (HORA_INICIO  VARCHAR2(15));

ALTER TABLE HOSPITALARIO.SNH_MST_ADMSRV_PROCEDIMIENTOS
 ADD (HORA_FIN  VARCHAR2(15));